server.port=8085
spring.application.name=naukri-service

user-service.base-url=${USER_SERVICE_BASE_URL:http://localhost:8082}
job-service.base-url=${JOB_SERVICE_BASE_URL:http://localhost:8083}

selenium.headless=false
naukri.max.pages=5

logging.level.com.jobautomation=DEBUG
